In [1]:
!apt-get update -qq
!apt-get install -y r-base -qq

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)


In [11]:


# ============================================================
# 1. CREATE MATRIX
# ============================================================

cat("\n\n[1] CREATE A MATRIX\n")
cat("------------------------------------------------------------\n")

x <- matrix(1:12, nrow = 4, ncol = 3)

cat("Matrix X:\n")
print(x)


# ============================================================
# 2. ROW AND COLUMN NAMES
# ============================================================

cat("\n\n[2] ROW AND COLUMN NAMES\n")
cat("------------------------------------------------------------\n")

rownames(x) <- c("r1", "r2", "r3", "r4")
colnames(x) <- c("c1", "c2", "c3")

print(x)


# ============================================================
# 3. MATRIX WITH SAME VALUE
# ============================================================

cat("\n\n[3] MATRIX WITH SAME VALUE\n")
cat("------------------------------------------------------------\n")

x <- matrix(2, nrow = 4, ncol = 2)

print(x)


# ============================================================
# 4. IDENTITY MATRIX
# ============================================================

cat("\n\n[4] IDENTITY MATRIX\n")
cat("------------------------------------------------------------\n")

I <- diag(1, nrow = 3, ncol = 3)

print(I)


# ============================================================
# 5. DIAGONAL MATRIX
# ============================================================

cat("\n\n[5] DIAGONAL MATRIX\n")
cat("------------------------------------------------------------\n")

D <- diag(5, nrow = 3, ncol = 3)

print(D)


# ============================================================
# 6. TRANSPOSE
# ============================================================

cat("\n\n[6] TRANSPOSE OF MATRIX\n")
cat("------------------------------------------------------------\n")

x <- matrix(1:8, nrow = 4, ncol = 2, byrow = TRUE)

cat("Original Matrix X:\n")
print(x)

cat("\nTranspose of X:\n")
print(t(x))


# ============================================================
# 7. ROW SUMS
# ============================================================

cat("\n\n[7] ROW SUMS\n")
cat("------------------------------------------------------------\n")

cat("Row sums:\n")
print(rowSums(x))


# ============================================================
# 8. COLUMN SUMS
# ============================================================

cat("\n\n[8] COLUMN SUMS\n")
cat("------------------------------------------------------------\n")

cat("Column sums:\n")
print(colSums(x))


# ============================================================
# 9. ROW MEANS
# ============================================================

cat("\n\n[9] ROW MEANS\n")
cat("------------------------------------------------------------\n")

cat("Row means:\n")
print(rowMeans(x))


# ============================================================
# 10. COLUMN MEANS
# ============================================================

cat("\n\n[10] COLUMN MEANS\n")
cat("------------------------------------------------------------\n")

cat("Column means:\n")
print(colMeans(x))


# ============================================================
# 11. MATRIX ACCESS
# ============================================================

cat("\n\n[11] MATRIX ACCESS\n")
cat("------------------------------------------------------------\n")

x <- matrix(1:15, nrow = 5, ncol = 3, byrow = TRUE)

cat("Matrix X:\n")
print(x)

cat("\nThird Row:\n")
print(x[3, ])

cat("\nSecond Column:\n")
print(x[, 2])

cat("\nRows 4-5 and Columns 2-3:\n")
print(x[4:5, 2:3])

cat("\nRows 1 & 4, Columns 1 & 3:\n")
print(x[c(1,4), c(1,3)])


# ============================================================
# 12. SCALAR ADDITION
# ============================================================

cat("\n\n[12] SCALAR ADDITION\n")
cat("------------------------------------------------------------\n")

x <- matrix(1:8, nrow = 4, ncol = 2, byrow = TRUE)

cat("X + 5:\n")
print(x + 5)


# ============================================================
# 13. SCALAR SUBTRACTION
# ============================================================

cat("\n\n[13] SCALAR SUBTRACTION\n")
cat("------------------------------------------------------------\n")

cat("X - 5:\n")
print(x - 5)


# ============================================================
# 14. SCALAR MULTIPLICATION
# ============================================================

cat("\n\n[14] SCALAR MULTIPLICATION\n")
cat("------------------------------------------------------------\n")

cat("5 * X:\n")
print(5 * x)


# ============================================================
# 15. SCALAR DIVISION
# ============================================================

cat("\n\n[15] SCALAR DIVISION\n")
cat("------------------------------------------------------------\n")

cat("X / 2:\n")
print(x / 2)


# ============================================================
# 16. MATRIX ADDITION
# ============================================================

cat("\n\n[16] MATRIX ADDITION\n")
cat("------------------------------------------------------------\n")

x <- matrix(1:8, nrow = 4, ncol = 2, byrow = TRUE)
y <- matrix(11:18, nrow = 4, ncol = 2, byrow = TRUE)

cat("Matrix X:\n")
print(x)

cat("\nMatrix Y:\n")
print(y)

cat("\nX + Y:\n")
print(x + y)


# ============================================================
# 17. MATRIX SUBTRACTION
# ============================================================

cat("\n\n[17] MATRIX SUBTRACTION\n")
cat("------------------------------------------------------------\n")

cat("X - Y:\n")
print(x - y)


# ============================================================
# 18. MATRIX MULTIPLICATION
# ============================================================

cat("\n\n[18] MATRIX MULTIPLICATION\n")
cat("------------------------------------------------------------\n")

x <- matrix(1:8, nrow = 4, ncol = 2, byrow = TRUE)
y <- matrix(11:18, nrow = 2, ncol = 4, byrow = TRUE)

cat("X %*% Y:\n")
print(x %*% y)

cat("\nY %*% X:\n")
print(y %*% x)


# ============================================================
# 19. X'X
# ============================================================

cat("\n\n[19] X'X\n")
cat("------------------------------------------------------------\n")

cat("Transpose(X) %*% X:\n")
print(t(x) %*% x)


# ============================================================
# 20. XX'
# ============================================================

cat("\n\n[20] XX'\n")
cat("------------------------------------------------------------\n")

cat("X %*% Transpose(X):\n")
print(x %*% t(x))


# ============================================================
# 21. CROSS PRODUCT
# ============================================================

cat("\n\n[21] CROSS PRODUCT\n")
cat("------------------------------------------------------------\n")

print(crossprod(x))


# ============================================================
# 22. ROW-WISE CONCATENATION
# ============================================================

cat("\n\n[22] ROW-WISE CONCATENATION - rbind()\n")
cat("------------------------------------------------------------\n")

x <- matrix(1:6, nrow = 3, ncol = 2, byrow = TRUE)
y <- matrix(11:16, nrow = 3, ncol = 2, byrow = TRUE)

print(rbind(x, y))


# ============================================================
# 23. COLUMN-WISE CONCATENATION
# ============================================================

cat("\n\n[23] COLUMN-WISE CONCATENATION - cbind()\n")
cat("------------------------------------------------------------\n")

print(cbind(x, y))


# ============================================================
# 24. MATRIX INVERSE
# ============================================================

cat("\n\n[24] MATRIX INVERSE\n")
cat("------------------------------------------------------------\n")

A <- matrix(
  c(84, 100,
    100, 120),
  nrow = 2,
  ncol = 2,
  byrow = TRUE
)

cat("Matrix A:\n")
print(A)

cat("\nInverse of A:\n")
print(solve(A))


# ============================================================
# 25. EIGENVALUES
# ============================================================

cat("\n\n[25] EIGENVALUES\n")
cat("------------------------------------------------------------\n")

e <- eigen(A)

cat("Eigenvalues:\n")
print(e$values)


# ============================================================
# 26. EIGENVECTORS
# ============================================================

cat("\n\n[26] EIGENVECTORS\n")
cat("------------------------------------------------------------\n")

cat("Eigenvectors:\n")
print(e$vectors)


# ============================================================
# 27. BASIC LOGICAL OPERATORS
# ============================================================

cat("\n\n[27] BASIC LOGICAL OPERATORS\n")
cat("------------------------------------------------------------\n")

a <- TRUE
b <- FALSE

cat("TRUE & FALSE = ")
print(a & b)

cat("TRUE | FALSE = ")
print(a | b)

cat("!TRUE = ")
print(!a)


# ============================================================
# 28. OR OPERATORS
# ============================================================

cat("\n\n[28] OR OPERATORS | AND ||\n")
cat("------------------------------------------------------------\n")

a <- 8
b <- 18

cat("8 < 10 || 8 < 2 = ")
print((a < 10) || (a < 2))

cat("18 < 10 || 18 < 2 = ")
print((b < 10) || (b < 2))

v <- c(8, 18)

cat("\nElement-wise OR using | :\n")
print((v < 10) | (v < 2))


# ============================================================
# 29. AND OPERATORS
# ============================================================

cat("\n\n[29] AND OPERATORS & AND &&\n")
cat("------------------------------------------------------------\n")

a <- 8
b <- 1

cat("8 < 10 && 8 > 2 = ")
print((a < 10) && (a > 2))

cat("1 < 10 && 1 > 2 = ")
print((b < 10) && (b > 2))

v <- c(8, 18, 1)

cat("\nElement-wise AND using & :\n")
print((v < 10) & (v > 2))


# ============================================================
# 30. LOGICAL FILTERING
# ============================================================

cat("\n\n[30] LOGICAL FILTERING\n")
cat("------------------------------------------------------------\n")

x <- 1:6

condition <- (x > 2) & (x < 5)

cat("Condition:\n")
print(condition)

cat("\nValues between 2 and 5:\n")
print(x[condition])


# ============================================================
# 31. OR FILTERING
# ============================================================

cat("\n\n[31] OR FILTERING\n")
cat("------------------------------------------------------------\n")

condition <- (x > 2) | (x < 5)

cat("Condition:\n")
print(condition)

cat("\nSelected values:\n")
print(x[condition])


# ============================================================
# 32. RELATIONAL OPERATORS
# ============================================================

cat("\n\n[32] RELATIONAL OPERATORS\n")
cat("------------------------------------------------------------\n")

cat("8 > 7  : "); print(8 > 7)
cat("7 < 5  : "); print(7 < 5)
cat("7 > 7  : "); print(7 > 7)
cat("7 >= 7 : "); print(7 >= 7)
cat("8 < 8  : "); print(8 < 8)
cat("8 <= 8 : "); print(8 <= 8)
cat("8 != 9 : "); print(8 != 9)
cat("9 != 9 : "); print(9 != 9)
cat("7 == 7 : "); print(7 == 7)
cat("7 == 8 : "); print(7 == 8)


# ============================================================
# 33. VECTOR COMPARISON
# ============================================================

cat("\n\n[33] VECTOR COMPARISON\n")
cat("------------------------------------------------------------\n")

x <- c(1, 2, 3)
y <- c(4, 5, 6)

cat("X > Y : ")
print(x > y)

cat("X < Y : ")
print(x < y)

cat("X != Y : ")
print(x != y)

cat("X == Y : ")
print(x == y)


# ============================================================
# 34. isTRUE() AND isFALSE()
# ============================================================

cat("\n\n[34] isTRUE() AND isFALSE()\n")
cat("------------------------------------------------------------\n")

cat("isTRUE(8 < 6)  : ")
print(isTRUE(8 < 6))

cat("isTRUE(8 > 6)  : ")
print(isTRUE(8 > 6))

cat("isFALSE(5 < 8) : ")
print(isFALSE(5 < 8))

cat("isFALSE(5 > 8) : ")
print(isFALSE(5 > 8))


# ============================================================
# 35. LOGICAL VARIABLES
# ============================================================

cat("\n\n[35] LOGICAL VARIABLES\n")
cat("------------------------------------------------------------\n")

x <- 5

Logical1 <- x > 2
Logical2 <- x < 10
Logical3 <- x != 5
Logical4 <- 2 * x > 11
Logical5 <- 3 * x < 20

cat("Logical1 = "); print(Logical1)
cat("Logical2 = "); print(Logical2)
cat("Logical3 = "); print(Logical3)
cat("Logical4 = "); print(Logical4)
cat("Logical5 = "); print(Logical5)





[1] CREATE A MATRIX
------------------------------------------------------------
Matrix X:
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12


[2] ROW AND COLUMN NAMES
------------------------------------------------------------
   c1 c2 c3
r1  1  5  9
r2  2  6 10
r3  3  7 11
r4  4  8 12


[3] MATRIX WITH SAME VALUE
------------------------------------------------------------
     [,1] [,2]
[1,]    2    2
[2,]    2    2
[3,]    2    2
[4,]    2    2


[4] IDENTITY MATRIX
------------------------------------------------------------
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


[5] DIAGONAL MATRIX
------------------------------------------------------------
     [,1] [,2] [,3]
[1,]    5    0    0
[2,]    0    5    0
[3,]    0    0    5


[6] TRANSPOSE OF MATRIX
------------------------------------------------------------
Original Matrix X:
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4